### PR TITLE
Exporting libraries correctly for package from quasimodo_models 

### PR DESCRIPTION
**Pull request by hawesie**
... then using them in quasimodo_brain. This can be improved more as all the _models libraries are included in catkin_LIBRARIES

### CODE REVIEW

**Comment by nilsbore** [comment]
Exporting the libraries should be the way to go. @jekekrantz Can you have a look, please?

**Comment by hawesie** [comment]
Please can this get merged soon?

**Comment by hawesie** [comment]
Because I can't test the updated bits on Betty without this.

**Comment by nilsbore** [comment]
Ok, merging this now!

**Pull request merged**
